### ISSUE TITLE
infinite loop if strategies are empty

### ISSUE THREAD

**Issue by kamilsk** [Rican7/retry#1]
https://github.com/Rican7/retry/blob/master/retry.go#L29-L35

**Comment by Rican7** [comment]
It only infinite loops if a non-zero error is always returned (never `nil`). That's intentional. You can limit the looping with the [`strategy.Limit`](https://github.com/Rican7/retry/blob/v0.1.0/strategy/strategy.go), otherwise it'll keep retrying until it's successful, by design.

**Comment by kamilsk** [comment]
yes, I agree, and for our internal transport client I wrote something like this:

```go
   if len(cfg.RetryStrategies) == 0 {
        result.retryStrategies = []strategy.Strategy{
            strategy.Limit(0),
        }
    } else {
        result.retryStrategies = cfg.RetryStrategies
    }
```

So, what you think if I modify `shouldAttempt` to handle this case more cleaner?

**Comment by Rican7** [comment]
Oh, I see. You were passing `strategy.Limit(0)` and expecting something different?

Not sure how this can be clearer.

**Comment by kamilsk** [comment]
`strategy.Limit(0)` run expected bad request one time (otherwise `retry` moves our tests to infinite loops).

**Comment by Rican7** [comment]
> `strategy.Limit(0)` run expected bad request one time (otherwise `retry` moves our tests to infinite loops).

That doesn't make sense, though. A "retry" library shouldn't only perform an action once by default. If _anything_, the `strategy.Limit` function should _maybe_ document that the limit should be greater than `0` for the function to actually perform a limitation.
