### ISSUE TITLE
Provide a Go module

### ISSUE THREAD

**Issue by CodyDWJones** [Rican7/retry#7]
The package can be imported into a module-using application as it is.  Making `retry` a module would help bring it up to date, though.

One benefit is developers relying on a fork could use the `replace` directive in their `go.mod` to point to their fork, without having to edit the package's own imports.

**Comment by kamilsk** [comment]
It's unnecessary because the module doesn't have any external dependencies and handled by the vgo gracefully.

**Comment by CodyDWJones** [comment]
> It's unnecessary because the module doesn't have any external dependencies and handled by the vgo gracefully.

That is true for developers importing Rican7's library.

It fails if someone forks the project to develop and test a PR. The Go source files have references to `github.com/Rican7` and `go get` follows those when the fork is imported into the dev's main project for testing.  It shouldn't be necessary to rewrite all the internal imports to contribute a PR.

**Comment by Rican7** [comment]
Thanks for this!
